project_id = "nreqgjyklsttdqwxhkps"

[functions.crop-recommendations]
verify_jwt = false

[functions.planting-guide]
verify_jwt = false

[functions.tree-recommendations]
verify_jwt = false

[functions.land-analysis]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false